import { IsArray, IsBoolean, IsNotEmpty, IsOptional, IsString } from "class-validator";
import { ApiProperty } from '@nestjs/swagger';

export class CreatePostDto {
    @ApiProperty({ description: 'The title of the post' })
    @IsString()
    @IsNotEmpty()
    title: string;

    @ApiProperty({ description: 'The content of the post' })
    @IsString()
    @IsNotEmpty()
    content: string;

    @ApiProperty({ description: 'The cover image URL', required: false })
    @IsString()
    @IsOptional()
    coverImage?: string;

    @ApiProperty({ description: 'List of tags for the post', type: [String] })
    @IsArray()
    @IsString({ each: true })
    tags: string[];

    @ApiProperty({ description: 'Draft status of the post' })
    @IsBoolean()
    @IsNotEmpty()
    isDraft: boolean;

    @ApiProperty({ description: 'Indicates if the post was generated by AI' })
    @IsBoolean()
    @IsNotEmpty()
    generatedByAI: boolean;
}

