import { PartialType } from '@nestjs/mapped-types';
import { CreatePostDto } from './create-post.dto';
import { IsOptional } from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';

export class UpdatePostDto {
    @ApiProperty({ description: 'The title of the post', required: false })
    @IsOptional()
    title?: string;

    @ApiProperty({ description: 'The content of the post', required: false })
    @IsOptional()
    content?: string;

    @ApiProperty({ description: 'The cover image URL', required: false })
    @IsOptional()
    coverImage?: string;

    @ApiProperty({ description: 'List of tags for the post', required: false, type: [String] })
    @IsOptional()
    tags?: string[];

    @ApiProperty({ description: 'Draft status of the post', required: false })
    @IsOptional()
    isDraft?: boolean;

    @ApiProperty({ description: 'Indicates if the post was generated by AI', required: false })
    @IsOptional()
    generatedByAI?: boolean;
}

